# Support Vector Machine

In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [2]:
df = pd.read_csv('Position_Salaries.csv')
df.head()

Position  Level  Salary
0   Business Analyst      1   45000
1  Junior Consultant      2   50000
2  Senior Consultant      3   60000
3            Manager      4   80000
4    Country Manager      5  110000

In [8]:
x = df.iloc[:,1:-1].values
y = df.iloc[:,-1].values

In [9]:
x

array([[ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10]])

In [7]:
y

array([  45000,   50000,   60000,   80000,  110000,  150000,  200000,
        300000,  500000, 1000000])

In [11]:
from sklearn.model_selection import train_test_split

In [12]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.25,random_state=0)

In [13]:
x_train

array([[10],
       [ 2],
       [ 7],
       [ 8],
       [ 4],
       [ 1],
       [ 6]])

In [14]:
x_test

array([[3],
       [9],
       [5]])

In [15]:
y_train

array([1000000,   50000,  200000,  300000,   80000,   45000,  150000])

In [16]:
y_test

array([ 60000, 500000, 110000])

In [17]:
from sklearn.preprocessing import StandardScaler

In [20]:
st = StandardScaler()
x_train = st.fit_transform(x_train)
x_test = st.transform(x_test)

In [21]:
x_train

array([[ 1.51524392],
       [-1.13643294],
       [ 0.5208651 ],
       [ 0.8523247 ],
       [-0.47351372],
       [-1.46789254],
       [ 0.18940549]])

In [22]:
x_test

array([[3.],
       [9.],
       [5.]])

# Using rbf kernel

In [26]:
from sklearn.svm import SVC

In [27]:
class_rbf = SVC(kernel='rbf',random_state=0)
class_rbf.fit(x_train,y_train)
y_predict_rbf = class_rbf.predict(x_test)

In [29]:
from sklearn.metrics import confusion_matrix

In [31]:
cm_rbf = confusion_matrix(y_test,y_predict_rbf)

In [32]:
cm_rbf

array([[0, 0, 0, 1],
       [0, 0, 0, 1],
       [0, 0, 0, 1],
       [0, 0, 0, 0]])

In [33]:
#classsification report

In [34]:
from sklearn.metrics import classification_report

In [37]:
class_r_rbf = classification_report(y_test,y_predict_rbf)

/home/sunil/.local/lib/python3.11/site-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/home/sunil/.local/lib/python3.11/site-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/home/sunil/.local/lib/python3.11/site-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/home/sunil/.local/lib/python3.11/site-packages/

In [39]:
print(class_r_rbf)

              precision    recall  f1-score   support

       60000       0.00      0.00      0.00       1.0
      110000       0.00      0.00      0.00       1.0
      500000       0.00      0.00      0.00       1.0
     1000000       0.00      0.00      0.00       0.0

    accuracy                           0.00       3.0
   macro avg       0.00      0.00      0.00       3.0
weighted avg       0.00      0.00      0.00       3.0

