In [1]:
import numpy as np
import pandas as pd

In [2]:
df = pd.DataFrame({'text':['people watch youtube','youtube watch youtube','people write comment','youtube write comment'], 'output':[1,1,0,0]})
df

text  output
0   people watch youtube       1
1  youtube watch youtube       1
2   people write comment       0
3  youtube write comment       0

# Bag of Words

In [3]:
from sklearn.feature_extraction.text import CountVectorizer

In [4]:
cv = CountVectorizer()

In [5]:
bow = cv.fit_transform(df['text'])

In [6]:
# vocab


print(cv.vocabulary_)

{'people': 1, 'watch': 2, 'youtube': 4, 'write': 3, 'comment': 0}


In [7]:
print(bow[0].toarray())
print(bow[1].toarray())

[[0 1 1 0 1]]
[[0 0 1 0 2]]


In [8]:
cv.transform(['youtube watch and write comment of youtube']).toarray()

array([[1, 0, 1, 1, 2]], dtype=int64)

# N-grams

In [9]:
 # ngram
    
    
cv = CountVectorizer(ngram_range=(2,2))

In [10]:
bow = cv.fit_transform(df['text'])

In [11]:
# Vocab

print(cv.vocabulary_)

{'people watch': 0, 'watch youtube': 2, 'youtube watch': 4, 'people write': 1, 'write comment': 3, 'youtube write': 5}


In [12]:
cv = CountVectorizer(ngram_range=(1,2))

In [13]:
bow = cv.fit_transform(df['text'])

In [14]:
print(cv.vocabulary_)

{'people': 1, 'watch': 4, 'youtube': 8, 'people watch': 2, 'watch youtube': 5, 'youtube watch': 9, 'write': 6, 'comment': 0, 'people write': 3, 'write comment': 7, 'youtube write': 10}


In [15]:
cv = CountVectorizer(ngram_range=(3,3))

In [16]:
bow = cv.fit_transform(df['text'])

In [17]:
print(cv.vocabulary_)

{'people watch youtube': 0, 'youtube watch youtube': 2, 'people write comment': 1, 'youtube write comment': 3}


In [18]:
cv = CountVectorizer(ngram_range=(1,3))

In [19]:
bow = cv.fit_transform(df['text'])

In [20]:
print(cv.vocabulary_)

{'people': 1, 'watch': 6, 'youtube': 10, 'people watch': 2, 'watch youtube': 7, 'people watch youtube': 3, 'youtube watch': 11, 'youtube watch youtube': 12, 'write': 8, 'comment': 0, 'people write': 4, 'write comment': 9, 'people write comment': 5, 'youtube write': 13, 'youtube write comment': 14}


# Tf-Idf

In [21]:
df

text  output
0   people watch youtube       1
1  youtube watch youtube       1
2   people write comment       0
3  youtube write comment       0

In [22]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [23]:
tfidf = TfidfVectorizer()
tfidf.fit_transform(df['text']).toarray()

array([[0.        , 0.61366674, 0.61366674, 0.        , 0.49681612],
       [0.        , 0.        , 0.52546357, 0.        , 0.8508161 ],
       [0.57735027, 0.57735027, 0.        , 0.57735027, 0.        ],
       [0.61366674, 0.        , 0.        , 0.61366674, 0.49681612]])

In [24]:
print(tfidf.idf_)

[1.51082562 1.51082562 1.51082562 1.51082562 1.22314355]


In [25]:
print(tfidf.get_feature_names_out())

['comment' 'people' 'watch' 'write' 'youtube']
